# Site settings
title: Ayo Isaiah
email: sudo@ayoisaiah.com
description: Software Developer and Writer
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ayoisaiah.xyz # the base hostname & protocol for your site
twitter_username: ayisaiah
github_username:  ayoisaiah

# Build settings
sass: 
  sass_dir: assets/sass
  style: :compressed
include: ["_pages"]
markdown: kramdown
kramdown: 
  input: GFM

#Analytics
google_analytics: UA-74640522-1

#Pagination
paginate: 20
paginate_path: "/blog/page:num"

defaults: 
  - 
    scope: 
      path: "" #All files in the project
      type: "posts"
    values: 
      layout: post

port: 4004

disqus: ayoisaiah
gems: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]

exclude: [node_modules, gulpfile.js]

